### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by fallbernana123456** [ariesssxu/vta-ldm#1]
使用 sh inference_from_video.sh 后，里面的 --original_args="ariesssxu/$model/summary.jsonl" 的配置有问题。修改了 vae_model 改为 ariesssxu/vta-ldm-clip4clip-v-large/audioldm-s-full.ckpt 
fea_encoder_name  改为 openai/clip-vit-large-patch14  报错 Segmentation fault      (core dumped)

**Comment by ariesssxu** [comment]
感谢提醒，已更新summary.jsonl，请git pull完后重试

**Comment by fallbernana123456** [comment]
> 感谢提醒，已更新summary.jsonl，请git pull完后重试

可以运行了。但是没太明白生成的是什么？要求原始视频是英文的吗？生成的音频是对视频的理解？配乐？即使是样例也没太明白想做什么。

**Comment by ariesssxu** [comment]
主要做的是音效生成
