### ISSUE TITLE
Question about the evaluation results

### ISSUE THREAD

**Issue by BingliangLi** [ariesssxu/vta-ldm#6]
Hi, thanks for opensource your code! I have a question about the evaluation results, in your paper Diff-foley only have 9.62 in IS score, this is far from the results in their paper, did you use the evaluation code from SpecVQGAN? In my own test their model can reach up to 45 IS score. 
Thanks, and good luck to your paper!
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/ae90dca8-4b75-45e6-b43c-0d6462c4804e">
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/f4ca6465-a0e4-470a-965f-6039834f69b9">

**Comment by ariesssxu** [comment]
Hi, the evaluation code we use is mainly adopted from audioldm's evaluation code ([this repo](https://github.com/haoheliu/audioldm_eval)). Notably, the Inception Score (IS) we achieved is competitive with the results presented in both [audioldm](https://arxiv.org/pdf/2301.12503) and [tango](https://arxiv.org/pdf/2404.09956), where the SOTA IS score hovers around 10. While I'm currently uncertain about the specific differences between the two versions of the evaluation codes, I am committed to investigating this matter further.
